### ISSUE TITLE
Resume after image is sent to displays

### ISSUE THREAD

**Issue by joekaiser** [TheFes/HA-configuration#54] opened 2022-08-10 13:46 UTC
Hey! I was able to get this working after just a few minutes of setup. Its great! Is there a way to have Resume work when I send an image to my google displays though?  

I have a script that, when the doorbell is pressed, a picture of the visitor is taken and cast to the google displays throughout the house. After 30s the image is removed. What would be the proper way to configure this so your resume script works? I have tried a few different ways, but my guess is that I need to update something in the automation you provide. Can you point me in the right direction? If it helps, here is my doorbell script.

Thanks so much! 💚 

```
doorbell_send_snapshot_to_displays:
  alias: Doorbell send snapshot to displays
  sequence:
  - service: camera.snapshot
    data:
      filename: /config/www/images/doorbellsnap.jpeg
    target:
      device_id: 4f727cb6d16f05386b5ab17047d76a08
  - service: media_player.play_media
    data:
      media_content_id: /local/images/doorbellsnap.jpeg
      media_content_type: image/jpeg
      announce: true
    target:
      entity_id:
      - media_player.office_display
      - media_player.kitchen_display
      - media_player.bedroom
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - service: media_player.turn_off
    data: {}
    target:
      entity_id:
      - media_player.kitchen_display
      - media_player.office_display
      - media_player.bedroom
  mode: single
```

**Comment by TheFes** [comment] 2022-08-10 18:16
Hi,
I've tested it myself. The problem is not that the automation does not trigger, because it does.
The problem is that casting an image to your Nest Hub doesn't change the state of the entity to `playing`, while it is showing the image, the state is `idle`. The Helper Script checks if the entity is playing and then waits until it is idle again to perform the resume.

The fact that the entity is not playing when showing the picture will present another issue, the script will not know what to wait for.

Let me think if I can find a workaround for this.

**Comment by TheFes** [comment] 2022-08-10 19:02
Okay, I might have found a workaround. The script will besides checking if the entity is playing, also check if there is a png or jpg/jpeg in the media_content_id. If so it will also perform te resume, but first wait 20 seconds.

This 20 second wait can be made configurable using a script variable

This also removes the need for the delay and turning off the entity in your script, this will be handled by the resume script. You only need the play_media service call.

You can test it by updating your script to v1.7.2b, which you will find here: https://github.com/TheFes/HA-configuration/blob/TheFes/issue54/include/script/00_general/google_cast/google_home_resume.yaml

**Comment by joekaiser** [comment] 2022-08-10 20:23
I tried that new script (and made sure to update my variables) but I just get this error now.

```
Logger: homeassistant.components.script.google_home_resume_helper
Source: helpers/script.py:405
Integration: Script ([documentation](https://www.home-assistant.io/integrations/script), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+script%22))
First occurred: 1:21:56 PM (2 occurrences)
Last logged: 1:21:56 PM

00 - Google Home Resume - Helper Script: If at step 1: Error executing script. Error for wait_template at pos 1: In 'template' condition: TypeError: argument of type 'NoneType' is not iterable
00 - Google Home Resume - Helper Script: Error executing script. Error for if at pos 1: In 'template' condition: TypeError: argument of type 'NoneType' is not iterable
```

**Comment by joekaiser** [comment] 2022-08-10 22:12
I rebooted my host and the problem is solved. (Note: I had tried restarting HASS several times and that didn't work)

Thanks for the tweak. This is so good. :)

**Comment by joekaiser** [comment] 2022-08-11 00:49
I take that back. It just started happening again 🤷  I'll see if I can figure it out.

**Comment by TheFes** [comment] 2022-08-11 05:40
It seems to be in the helper script, could you send me a trace of that script

**Comment by TheFes** [comment] 2022-08-11 06:48
Never mind, I think I fixed it now. Could you check v2.7.2b2 (same link as before)
The problem was I did not check if the attribute `media_content_id` existed before checking for an image extension in the attribute contents.

**Comment by TheFes** [comment] 2022-08-11 06:54
Added a variable `image_delay` in the script configuration, default setting if not set is 20 seconds, but you can use it to configure the delay which will be added before the resume in case an image is casted.

**Comment by TheFes** [comment] 2022-08-12 11:19
@joekaiser were you already able to test the new version? If everything works fine, I can merge it with the main branch.

**Comment by joekaiser** [comment] 2022-08-12 13:16
Sorry, I left for the weekend and won't be home until Sunday PDT. I'll give it a test as soon as I can.

**Comment by TheFes** [comment] 2022-08-12 13:47
Okay, no worries! Take your time!

**Comment by joekaiser** [comment] 2022-08-15 16:29
No, it isn't working but I think it is close. 

Logs:
``` 
WARNING
Logger: homeassistant.helpers.template
Source: helpers/template.py:141
First occurred: 9:25:48 AM (1 occurrences)
Last logged: 9:25:48 AM

Template variable warning: 'image_delay' is undefined when rendering '{{ image_delay }}'


ERROR
Logger: homeassistant.components.script.google_home_resume_helper
Source: helpers/script.py:405
Integration: Script ([documentation](https://www.home-assistant.io/integrations/script), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+script%22))
First occurred: 9:25:48 AM (1 occurrences)
Last logged: 9:25:48 AM

00 - Google Home Resume - Helper Script: If at step 1: If at step 5: Error rendering 00 - Google Home Resume - Helper Script: If at step 1: If at step 5 delay template: offset should be format 'HH:MM', 'HH:MM:SS' or 'HH:MM:SS.F'
```

I used your latest script and I'm going through it now to check variables and wait format.

**Comment by joekaiser** [comment] 2022-08-15 16:32
My hunch is that this line `image_delay: "{{ image_delay if image_delay is defined and image_delay else 20 }}"` is using the default of `20` but the reference to that variable needs `seconds: 20` 

```
  - if: "{{ image }}"
          then:
            - delay: "{{ image_delay }}"
```

**Comment by joekaiser** [comment] 2022-08-15 16:44
OK, yes hard coding the delay to `seconds: 20` on that line fixed the issue and the script works about 60% of the time. I'll share the logs here but I wouldn't be surprised if these were a symptom of my setup; not the script.

**(to be clear, it still works, these errors are just logged)**

```
ogger: homeassistant
Source: helpers/template.py:423
First occurred: 9:37:31 AM (1 occurrences)
Last logged: 9:37:31 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 421, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1906, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 4, in top-level template code
TypeError: argument of type 'NoneType' is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 428, in _async_run
    return await self.script.async_run(script_vars, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 919, in _async_if_step
    await self._async_run_script(if_data["if_then"])
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1025, in _async_run_script
    await self._async_run_long_action(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 644, in _async_run_long_action
    long_task.result()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 988, in _async_variables_step
    self._variables = self._action[CONF_VARIABLES].async_render(
  File "/usr/src/homeassistant/homeassistant/helpers/script_variables.py", line 62, in async_render
    rendered_variables[key] = template.render_complex(
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 141, in render_complex
    return value.async_render(variables, limited=limited, parse_result=parse_result)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 423, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: argument of type 'NoneType' is not iterable


Logger: homeassistant.components.script.google_home_resume_helper
Source: helpers/script.py:405
Integration: Script ([documentation](https://www.home-assistant.io/integrations/script), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+script%22))
First occurred: 9:37:31 AM (2 occurrences)
Last logged: 9:37:31 AM

00 - Google Home Resume - Helper Script: If at step 1: Error executing script. Error rendering template for variables at pos 2: TypeError: argument of type 'NoneType' is not iterable
00 - Google Home Resume - Helper Script: Error executing script. Error rendering template for if at pos 1: TypeError: argument of type 'NoneType' is not iterable
```

**Comment by TheFes** [comment] 2022-08-15 20:09
Both 
```yaml
delay: 20
```
and 
```yaml
delay:
  seconds: 20
``` 
are valid, and both are a 20 second delay.
But I will have a second look.

Thanks for testing!

**Comment by TheFes** [comment] 2022-08-16 07:51
I added this line `image_delay: "{{ image_delay if image_delay is defined and image_delay else 20 }}"` on the wrong location. It was added for the Ytube Music Player resume, and it should have been added on another service call for the helper script. That is fixed now.

I think I also fixed the error in the log you posted above. Coud you please test 2.7.2b3 which I just uploaded. Same link again :)

**Comment by joekaiser** [comment] 2022-08-16 16:11
It seems to be working 🙌  Thanks for all your help!

**Closed as completed** 2022-08-18 10:21 UTC
Labels: enhancement, google home scripts
