### ISSUE TITLE
Multiple Spotcast accounts and media_player.group

### ISSUE THREAD

**Issue by johannwilken** [TheFes/HA-configuration#2] opened 2021-12-27 12:04 UTC
Good day Fes,

Sorry for bugging you again. This is not urgent, but I have 2 questions:

1. When playing 1 spotcast account per speaker at a time it works 100% and resumes with the spotcast account that was playing. When Playing music from 2 spotcast accounts on 2 media players, when notification plays and the music resumes it only resumes on the default spotcast account on the last speaker the script ran.  I tried running a script per speaker pointing to different default spotcast account, didn't work.  How can I setup my automation to resume both speakers with the 2 spotcast accounts that was playing?

2. When spotcast to media_player.group (my own group created in google home app) and the notification plays, the music resumes only on one speaker.  I think i'm setting up the script wrong.

Thank you in advance.

**Comment by TheFes** [comment] 2021-12-27 18:57
Hi,

Could you share a trace from when it does not work properly? Both multiple spotcast accounts, and resuming of speaker groups should work.

You can go to Configuration > Automation & Scenes > Scripts and then press the button with the clock with the arrow around it to open the debug trace. In the top right corner there is a download buttoen.

You can attach it to your reply by dragging it on the the reply screen.

**Comment by johannwilken** [comment] 2021-12-28 14:10
Hi Fes,

Thanks for your reply.

Screenshot 1:

Spotcast to media_player.group. Only one speaker resume.

Screenshot2:

2 Spotcast accounts to 2 speakers. Only one resume, but with the music that was playing on the speaker that didn't resume.
![Screenshot 1(media_player group)](https://user-images.githubusercontent.com/65971874/147574701-8c148d45-0a9e-431b-a173-558315968679.png)
![Screenshot 2(2 spotcast accounts on 2 speakers)](https://user-images.githubusercontent.com/65971874/147574705-88dcde8a-73c8-44eb-aded-7dc73a8ae2a8.png)

Thanks for checking it out for me

**Comment by johannwilken** [comment] 2021-12-28 14:19
Hare are the screenshots of the edited Script and script calls from node-red. 

![edited Script ](https://user-images.githubusercontent.com/65971874/147575479-2833cf51-53df-4933-b9a4-11c028d7a6f8.png)
![Node-Red Script call for master bedroom speaker](https://user-images.githubusercontent.com/65971874/147575486-47c5485b-6e2f-4448-b9b5-67d0cf5b26cf.png)
![Node-Red Script call for kitchen display](https://user-images.githubusercontent.com/65971874/147575491-36d7e05d-b091-4ad4-9cbe-36658bddf926.png)

**Comment by TheFes** [comment] 2021-12-28 18:40
Sorry, could you download the trace and upload it? After pressing the download button you should get a json file

**Comment by johannwilken** [comment] 2021-12-29 04:50
Good morning Fes,

Herewith the json files. Thank you for your time

[json.zip](https://github.com/TheFes/HA-configuration/files/7787362/json.zip)
.

**Comment by TheFes** [comment] 2021-12-29 18:50
Are you sure the `spotify_media_players` are set up correct?
I can see in the trace it determined correctly that Spotify was playing, but it could not retrieve any information from the players:
`"spotify_players_info": []`

What do you get when you search for `media_player.spotify` in developer tools > states

This is what I get, and this matches my `spotify_media_players` setting
![Screenshot_20211229-221852](https://user-images.githubusercontent.com/28803438/147704208-534f622d-e27f-4443-94ce-08f9a65e1ad3.png)

**Comment by johannwilken** [comment] 2021-12-30 04:39
Good morning Fes,

Herewith screenshots of my config and media players. Is it setup right?

I am able to  spotcast from any of the two accounts with no problems. Each spotcast account points to its own spotify developers app. 

Thank you and hope you have a great day

![Spotify and Spotcast Config](https://user-images.githubusercontent.com/65971874/147722145-02c9474a-f1d1-4393-8414-896199f60e11.PNG)
![Spotify in HA](https://user-images.githubusercontent.com/65971874/147722153-4f74c3f1-d425-4b0c-b900-c46f13770688.PNG)
![Spotify media players in HA](https://user-images.githubusercontent.com/65971874/147722154-a677f8dd-c6b2-49a6-b351-a9990d9721d6.PNG)
.

**Comment by TheFes** [comment] 2021-12-30 08:51
Thanks for the information.
I did see there was something wrong with the template which determines which spotcast account should be used. I also did not take into account that the spotcast account could consist of two parts.
I will fix that when I find some time. Maybe this evening or tomorrow, otherwise Monday.

However, that doesn't explain why the spotify_player_info returns an empty list.
Could you try to play something on both accounts, and then paste the following template in developer tools > templates.
 ```
          {% 
            set spotify_player_list = states.media_player 
                                        | selectattr('state', 'eq', 'playing')
                                        | selectattr('entity_id', 'search', 'media_player.spotify') 
                                        | map(attribute='entity_id') 
                                        | list
          %}
          {% set entities = expand(spotify_player_list) %}
          {% set ns = namespace(info=[]) %}
          {% for entity in entities %}
            {% set ns.info = ns.info + [ dict(entity_id=entity.entity_id, source=entity.attributes.source) ] %}
          {% endfor %}
          {{ ns.info }}
```

**Comment by johannwilken** [comment] 2021-12-30 09:03
Hi Fes,

Herewith the screenshots.

2 Accounts on 2 speakers:
![2 spotify accounts on 2 speakers](https://user-images.githubusercontent.com/65971874/147737166-a8d65b4d-8d8a-44f5-b84e-b8287caaba8f.PNG)

Playing to media_player.group: 

Only displaying 1 speaker (spotcast to media_player.wilken_speakers)
![1 spotcast account playing to media_player group](https://user-images.githubusercontent.com/65971874/147737252-dd6e2ee3-1270-4145-b451-3de7617c1b3d.PNG)
![Entities playing](https://user-images.githubusercontent.com/65971874/147737255-09241d3a-598b-4225-977d-65951839acee.PNG)

Thank you

**Comment by TheFes** [comment] 2021-12-30 09:24
Okay, this is as expected.
Then I do wonder why the list was empty in your trace, as it used the exact same template.

Let's try again after I corrected the template for the spotcast account. Will get back to you asap

**Comment by johannwilken** [comment] 2021-12-30 09:37
Thank you Fes,. No hurry, only when you have time.

**Comment by TheFes** [comment] 2021-12-31 14:33
Made a couple of changes:
* Fixed some bugs in template to determine spotcast account
* Removed the `spotify_media_players` variable as it was not used anyway

Can you test if it works now? Please note it takes a short time before the Spotify media_players are updated, and actually show that they are playing. So don't start the script immediately after you started the Spotify stream. If you want to be sure, you can check in dev tools > states if they are playing.

**Comment by johannwilken** [comment] 2021-12-31 15:37
Hi Fes,

Happy new year to you and your family.

I'm just sending findings as I'm testing, please enjoy new year first.

Test 1:
Playing with 2 spotcast accounts to 2 speakers. 
MB speaker - was playing with media_player.spotify_johann_wilken
Kitchen display - was playing with media_player.spotify_elandi

After script run:

MB speaker - did not resume
Kitchen display - resumed with media_player.spotify_johann_wilken instead of media_player.spotify_elandi

![Spotify Media Players](https://user-images.githubusercontent.com/65971874/147830127-ea77c65c-41ca-4c4c-8a5f-cdb0b6044261.JPG)

[Test 1.zip](https://github.com/TheFes/HA-configuration/files/7796506/Test.1.zip)

Test2:
Playing 1 account on mb_speaker:
Get error and don't resume
It seems that the speaker without screen won't resume.

Playing on kitchen_display with media_player.spotify_elandi:
resumes but with media_player.spotify_johann_wilken instead of media_player.spotify_elandi
(Looks like it always resume with the default account)

[Test2.zip](https://github.com/TheFes/HA-configuration/files/7796509/Test2.zip)

Test3:

Group -media_player.wilken_speakers
Media Player: media_player.spotify_johann_wilken

mb_speaker - did not resume
kitchen_display - resumed

![mediaplayers](https://user-images.githubusercontent.com/65971874/147830745-0b9e51dc-72d5-4b97-9a8e-51b6bc0ee656.JPG)

[Test3.zip](https://github.com/TheFes/HA-configuration/files/7796529/Test3.zip)

**Comment by TheFes** [comment] 2021-12-31 19:02
Thanks for testing and providing the traces.
This will be something for next year, we're in the last hours of 2021 here.

Happy New Year for you and your family as well!

**Comment by TheFes** [comment] 2022-01-01 19:23
Hi,

I've looked into your test files:

1)
Your 'speaker_groups` variable is not set up correct. You have:
```yaml
speaker_groups:
  media_player.huis_groep:
    - media_player.kitchen_display
    - media_player.mater_bedroom_speaker
```
But the group is not called `media_player.huis_groep`, but apparantly `media_player.wilken_speakers`
And there seems to be a typo in 'media_player.mater_bedroom_speaker`

Seccondly, your spotcast integration doesn't seem to be set up like you provided in the script.
It should be like this:
```yaml
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  accounts:
    johan_wilken:
      sp_dc: !secret sp_dc_jw
      sp_key: !secret sp_key_jw
```
You provided `elandi` as the `primary_spotcast` account, so that should be the account which does not have the account name specified. 

Based from your test results, it seems the `johan_wilken` spotify account is actually the primary account, which doesn't have an account name.

Could you please look into this, and let me know if that solves it?

Please also look into the other variables, I don't think you need the `fixed_picture` for `Radio 2`  (if you don't use it, you can remove that part totally) and I doubt if you placed a silent mp3 on the exact same location as I did.

**Comment by TheFes** [comment] 2022-01-01 20:28
Oh sorry, you already provided the spotcast settings on an earlier post.
Your primary spotcast account indeed appears to be the account of Johan.
As the spotify media player belonging to that account ends with `johan_wilken` you should use that as `primary_spotcast`

**Comment by johannwilken** [comment] 2022-01-02 04:20
Good Morning Fes,

Hope you and your Family had a great New Years?

Thank you for the reply.

Sorry for the edited. I forgot that when I tested to see if I can make it work, I changed those options.

I tested now with the changes you suggested and its working like a charm. Only One
scenario still an issue:

When casting to media_player.wilken_speakers (Google home created group), the script run and tries to resume on both speakers (so the script is working), but then stops on one speaker as spotify picks up that 1 account wants to play on two speakers. If you see the below sceenshot (your old template), there is only 1 media player active when casting to media_player.wilken_speakers.

Your template in developers:
![Kitchen Display](https://user-images.githubusercontent.com/65971874/147866138-c913068c-69e0-446e-89da-93b11cf61915.JPG)

Actual active media players:
![mediaplayers](https://user-images.githubusercontent.com/65971874/147866046-70d4cb58-9138-4f5a-b51f-d536cbde3b33.JPG)

Is there a way for the script to resume to the media_player.wilken_speakers group?

Thank you Fes, I appreciate your time.

**Comment by TheFes** [comment] 2022-01-02 13:39
It should, could you provide the json for this test scenario?

**Comment by johannwilken** [comment] 2022-01-02 13:58
Hi Fes,

Herewith screenshots and json files.

Before script run:
![Developers - Template](https://user-images.githubusercontent.com/65971874/147878100-37a35bf9-f809-4689-a1f0-bfcac80a7fd9.JPG)
![active mediaplayers](https://user-images.githubusercontent.com/65971874/147878103-2b254210-7784-47b2-b409-e516083e433e.JPG)

After Script run:

![Developers - Template after script run](https://user-images.githubusercontent.com/65971874/147878109-3ff601fc-8e3b-438b-9f43-5ec74c5af2b5.JPG)
![active mediaplayers after script run](https://user-images.githubusercontent.com/65971874/147878112-ddfbd992-8f6e-421c-86e0-6ca66177aaa9.JPG)

Json Files:

[Jsons.zip](https://github.com/TheFes/HA-configuration/files/7799157/Jsons.zip)

Should my group be added to the script somehow?

Thank you

**Comment by TheFes** [comment] 2022-01-02 14:56
It seems you missed the part about the speaker group in my previous comment:

You know have:
```yaml
speaker_groups:
  media_player.huis_groep:
    - media_player.kitchen_display
    - media_player.mater_bedroom_speaker
```

You should have:
```yaml
speaker_groups:
  media_player.wilken_speakers:
    - media_player.kitchen_display
    - media_player.mater_bedroom_speaker
```

**Comment by johannwilken** [comment] 2022-01-02 15:12
Hi Fes,

Changed media_player.wilken_speakers and now the music doesn't resume at all.

![Script config](https://user-images.githubusercontent.com/65971874/147880069-b4337c9e-b911-4afd-9918-7269dec16b3a.JPG)

[json files.zip](https://github.com/TheFes/HA-configuration/files/7799256/json.files.zip)

Thank you

**Comment by johannwilken** [comment] 2022-01-02 15:37
Hi Fes,

I have run test again, got a different error from my last previous post. Now it has a reference to
the media_player.wilken_speakers group.

[New json files.zip](https://github.com/TheFes/HA-configuration/files/7799309/New.json.files.zip)

The kitchen_display shows the spotify logo but doesn't play anything. When the casting a single account to any 1 of the 2 speakers, the group continue but with the new playlist. It is a weird one. I also needs to stop the cast to the wilken_speakers group in the google home app before I can cast to a single speaker, otherwise it keeps casting to the group. I don't know if this is a spotcast issue perhaps?

Hope this helps.

Thank you

**Comment by TheFes** [comment] 2022-01-02 20:15
Hi, 

The script now does what it's supposed to. The error mentioned in the script is caused by spotcast.
I can see the friendly name of the group entity is `Wilken Speakers`. Is it also named like that in the Google Home app? Because they need to be exactly the same.

You could install the spotcast sensor, and see what it returns. Does it show your speaker group in there?
https://github.com/fondberg/spotcast#use-the-sensor

**Comment by johannwilken** [comment] 2022-01-03 16:20
Hi Fes,

The name of the group is the same:

![Screenshot_20220102-222316_Home](https://user-images.githubusercontent.com/65971874/147953215-749385e5-7706-46c5-85cc-1f1a3d1c8b56.jpg)

Sensor - Chromecast devices:

![sensor - chromecast devices](https://user-images.githubusercontent.com/65971874/147954061-c38dca1e-44c7-40ad-9ffe-aba99105ab08.PNG)

Anything else I must try?

Thank you

**Comment by TheFes** [comment] 2022-01-04 19:58
I don't  see anything strange with the group or the sensor data.

Does it also give the same error when you go to Developer Tools > Services and then provide the following service data in YAML mode:
```yaml
service: spotcast.start
data:
  entity_id: media_player.wilken_speakers
  force_playback: true
```

If I try that with a speaker group it works fine.

If that also doesn't work for you, you can maybe try to recreate the speaker group in the Google Home app, and check if that helps. Or create an issue on the spotcast github page, mentioning a direct service call from developer tools > services does not work (I think referring to this script will only cause confusion).

**Comment by johannwilken** [comment] 2022-01-05 03:51
Good morning Fes,

Hope you have a great week so far?

I have actually setup transfer music based on room presence just yesterday. I have tried the force__playback to the group and that works 100%. 

Rerun the script and same issue before. The speakers group goes on, but doesn't resume.  

Then I tested by only calling the script to 1 speaker and after the tts message the group resumes. It seems the parallel runs of the script is causing this issue.

How do you recommend I use the script in my automation for TTS massage to both speakers, or is this why the script can run in parallel?

Thank you and kind regards,

**Comment by TheFes** [comment] 2022-01-05 18:51
Aaaah, now I finally understand why you keep sending 2 json files for each test case, you run the script twice, once for every speaker.

You don't have to do that, you can provide a list of tts_targets
```yaml
- service: script.tts_and_spotify_resume
  data:
    tts_message: "Patio Door 1 still open."
    tts_target:
      - media_player.kitchen_display
      - media_player.master_bedroom_speaker
    tts_volume: 50
    restore_volume_all: True
    volume_non_playing: 25
    speaker_group_split: True
```

And, because you apparantly set `speaker_group_split` to `True`, you will achieve exactly the same result when you use the speaker group as target, as with that setting, it will send the tts message to the separate members of the speaker group.

But there is no need to start the script once for each speaker, with the same message at the same time.

Oh, and `True` for `restore_volume_all` and `speaker_group_split` should not be quoted. They are treated as strings then, and they should be boolean values.

**Comment by TheFes** [comment] 2022-01-06 15:38
I just published a change which makes resuming non playing entities a lot faster, if you update to this version `restore_volume_all` and `volume_non_playing` are depreciated. Volume restore of non playing entities will only result in a delay of 0.25 seconds, so I did not see the point in making settings for this, it is now always done in case there are non playing entities.

So in that case you can use this action:
```yaml
- service: script.tts_and_spotify_resume
  data:
    tts_message: "Patio Door 1 still open."
    tts_target:
      - media_player.kitchen_display
      - media_player.master_bedroom_speaker
    tts_volume: 50
    speaker_group_split: True
```

or

```yaml
- service: script.tts_and_spotify_resume
  data:
    tts_message: "Patio Door 1 still open."
    tts_target: media_player.wilken_speakers
    tts_volume: 50
    speaker_group_split: True
```

**Comment by johannwilken** [comment] 2022-01-06 17:17
Hi Fes,

I have updated the script to the latest config. Here is my findings:
Sorrry for all the test, but wants to give you enough info as possible

**Multiple media players:**
![Trigger config](https://user-images.githubusercontent.com/65971874/148423270-a93d25c1-02c3-4645-933b-8846662acf6f.JPG)

Test 1:
johann_wilken on master_bedroom_speaker - resumes 100%

Test 2:
johann_wilken on kitchen_display - did not resume
[Test2.zip](https://github.com/TheFes/HA-configuration/files/7823514/Test2.zip)

Test 3:
elandi on kitchen_display - did not resume
[Test3.zip](https://github.com/TheFes/HA-configuration/files/7823533/Test3.zip)

Test 4:
elandi on master_bedroom_speaker - did resume 100%
[Test4.zip](https://github.com/TheFes/HA-configuration/files/7823549/Test4.zip)

Test 5:
johann_wilken on wilken_speakers (group) - did resume 100%
[Test5.zip](https://github.com/TheFes/HA-configuration/files/7823568/Test5.zip)

Test 6:
elandi on wilken_speakers (group) - did not resume
[Test6.zip](https://github.com/TheFes/HA-configuration/files/7823580/Test6.zip)

**Single media player:**
![Trigger config single media_player](https://user-images.githubusercontent.com/65971874/148423905-36d1b791-8e0d-495c-bab3-d035f2cab92c.JPG)

Test 7: 
elandi on kitchen_display - did resume 100% (test 3 it didn't)
[Test7.zip](https://github.com/TheFes/HA-configuration/files/7823628/Test7.zip)

Test 8:
johann_wilken on kitchen_display - did resume 100% (test 2 it didn't)
[Test8.zip](https://github.com/TheFes/HA-configuration/files/7823683/Test8.zip)

Test 9:
johann_wilken on wilken_speakers - did not resume
[Test9.zip](https://github.com/TheFes/HA-configuration/files/7823697/Test9.zip)

It looks like when having multiple media players under tts_target it only resume on one of them, but when wilken_speakers group is playing it resumes to the group again. Where as when you call the script for each speaker it resume 100%, but then the group does not resume.

**Comment by TheFes** [comment] 2022-01-06 19:28
I'll look into it tomorrow, basically all this should work :)

**Comment by TheFes** [comment] 2022-01-06 20:37
Okay, I've had a look:

2)  2 of the 3 files in this zip seem to be quite old (dated 31st of december). In the other one there was nothing to resume according to the script.

3) Again two old files in the zip, in the other one nothing was playing according to the script.

6) The script did send the correct action to resume de `elandi` account on `media_player.wilken_speakers`, and the script ran without issues. Can't give you any further information about this one.

9) Similar as 6, action to resume `johann_wilken` account on `media_player.wilken_speakers` was sent. No errors in the script.

As I don't see any errors, and since in case 6 and 9 the right action was sent, I'm not sure how I can fix this.

**Comment by johannwilken** [comment] 2022-01-06 21:30
Hi Fes,

I'm really sorry. I don't know why there is older jdon files in the last
thread. I will have a look, what is weird is I saved the json files and
added to the thread as I was testing.

Waiting know at the airport, picking up the wife and kids.

Sorry again.

**Comment by TheFes** [comment] 2022-01-07 07:46
No problem! 

Say hi to them from me 😉 
```yaml
- service: script.tts_and_spotify_resume
  data:
    tts_message: "Hi!"
    tts_target: media_player.wilken_speakers
    tts_volume: 50
    speaker_group_split: True
```

**Comment by johannwilken** [comment] 2022-01-08 08:26
Good morning Fes,

Lets try again, I double check times and took screenshots of the time of script runs (added in zip file).

Findings:
1. It looks like when having multiple media players added to the service call it only resume to the bottom media player in the list.
  Test 1-6: media_player.master-bedroom_speaker @ the bottom of the list.
  Test 10-13 and 14: media_player.kitchen_display @ the bottom of the list.

2. For some reason when playing to media_player.wilken_speakers works 100% in any scenario, where in me previous post it didn't.

**Tests conducted:**

**Multiple media players:**
![Test 1 Service Call](https://user-images.githubusercontent.com/65971874/148635186-37556515-f074-4879-ae75-975b68877743.JPG)

Test 1:
johann_wilken on master_bedroom_speaker - did resume 100%
[Test 1.zip](https://github.com/TheFes/HA-configuration/files/7832780/Test.1.zip)

Test 2:
johann_wilken on kitchen_display - did not resume
[Test 2.zip](https://github.com/TheFes/HA-configuration/files/7832788/Test.2.zip)

Test 3:
elandi on kitchen_display - did not resume
[Test 3.zip](https://github.com/TheFes/HA-configuration/files/7832795/Test.3.zip)

Test 4:
elandi on master_bedroom_speaker - did resume 100%
[Test 4.zip](https://github.com/TheFes/HA-configuration/files/7832801/Test.4.zip)

Test 5:
johann_wilken on wilken_speakers (group) - did resume 100%
[Test 5.zip](https://github.com/TheFes/HA-configuration/files/7832803/Test.5.zip)

Test 6:
elandi on wilken_speakers (group) - did resume 100%
[Test 6.zip](https://github.com/TheFes/HA-configuration/files/7832805/Test.6.zip)

**Multiple Media Players flipped:** 
![Service call _ multiple media players flipped](https://user-images.githubusercontent.com/65971874/148636471-a1aecc91-7372-4961-b5ae-b8504af9f835.JPG)

Test 10:
johann_wilken on master_bedroom_speaker - did not resume (did resume 100% in Test 1)
[Test 10.zip](https://github.com/TheFes/HA-configuration/files/7832835/Test.10.zip)

Test 11:
johann_wilken on kitchen_display - did resume 100% (did not resume in Test2)
[Test 11.zip](https://github.com/TheFes/HA-configuration/files/7832842/Test.11.zip)

Test 12:
elandi on kitchen_display - did resume 100% (did not resume in Test3)
[Test 12.zip](https://github.com/TheFes/HA-configuration/files/7832844/Test.12.zip)

Test 13:
elandi on master_bedroom_speaker - did not resume (did resume 100% in Test4)
[Test 13.zip](https://github.com/TheFes/HA-configuration/files/7832896/Test.13.zip)

-----------------------------------------------------------------------------
**Single media player:**
![Sevice call single media player](https://user-images.githubusercontent.com/65971874/148635897-d235823a-79a2-4db2-90d7-8399982af650.JPG)

Test 7:
johann_wilken on kitchen_display - did resume 100% (test 2 it didn't)
[Test 7.zip](https://github.com/TheFes/HA-configuration/files/7832820/Test.7.zip)

Test 8:
elandi on kitchen_display - did resume 100% (test 3 it didn't)
[Test 8.zip](https://github.com/TheFes/HA-configuration/files/7832822/Test.8.zip)

Test 9:
johann_wilken on wilken_speakers - did resume 100%
[Test 9.zip](https://github.com/TheFes/HA-configuration/files/7832825/Test.9.zip)

-----------------------------------------------------
**Multiple Spotcast accounts on Multiple Media Players:**
![Service call _ multiple media players flipped](https://user-images.githubusercontent.com/65971874/148637427-84b347aa-0e6c-4691-aff9-5c291833378f.JPG)

Test 14:
elandi on media_player.kitchen_display and johann_wilken on media_player.master_bedroom_speaker - only resumed on media_player.kitchen_display
[Test 14.zip](https://github.com/TheFes/HA-configuration/files/7832886/Test.14.zip)

**Comment by TheFes** [comment] 2022-01-08 22:02
Hi, 

The common thing in all the times the script did not resume, is that the script doesn't recognize there is something to resume at all.

Could you please try the following, replace this part (which determines the entities to resume) with the part below.
Basically the second code block splits the template into separate part, which will allow me to see what exactly goes wrong here. I also added a variable which will return the state of all `media_player` entities in your config.

After that please run some more tests, and provide me the json files. The screenshots are not needed, that information is also in the json.

You can replace only the specific part which is changes (using the code blocks below), or you can replace the entire sequence part with the code from this link: https://www.codepile.net/pile/dvzMeoPB

So replace this (line 98 to 173 in my script, could be a little bit different your config) (or use the link above)
```yaml
        players_to_resume: >
          {# use data from google_home_say_voice script in case it was used #}
            {% if voice_media_player_data is defined %}
              {{ voice_media_player_data }}
            {% else %}
              {# determine which media_players are playing and store attributes#}
                {% 
                  set all_players_playing = states.media_player 
                                              | selectattr('state', 'eq', 'playing') 
                                              | map(attribute='entity_id') 
                                              | list  
                %}
          {# determine which Google Home speakers groups are playing #}
                {% 
                  set all_speaker_groups_playing =  voice_groups | default(
                                                    all_players_playing 
                                                      | select('in', speaker_group_list) 
                                                      | list )
                %}
              {# determine which of the tts_targets (including groups members) are playing  #}
                {% set ns = namespace(tts_targets = []) %}
                  {% for target in tts_target_list %}
                    {% set ns.tts_targets = ns.tts_targets + speaker_groups[target] if target in speaker_group_list else [ target ] %}
                  {% endfor %}
                {% set tts_playing = ns.tts_targets | select('in', all_players_playing) | list %}
              {# determine which groups should be resumed becaue a single tts target is part of that group #}
                {% set ns = namespace(groups = []) %}
                  {% for group in all_speaker_groups_playing %}
                    {% for entity in speaker_groups[group] if entity in tts_playing %}
                      {% set ns.groups = ns.groups + [group] %}
                    {% endfor %}
                  {% endfor %}
                {% set speaker_groups_resume = ns.groups | unique | list %}
              {# determine if tts target has subgroups which are playing and add to speaker_groups_resume #}
                {% set ns = namespace(groups = []) %}
                  {% for target in tts_target_list %}
                    {% set ns.groups = ns.groups + 
                        (sub_groups[target] | select('in', all_speaker_groups_playing) | list)
                        if sub_groups is defined else []     
                  %}
                  {% endfor %}
                {% set speaker_groups_resume = speaker_groups_resume + ns.groups | unique | list %}
              {# determine which single entities are in a group which is going to be resumed #}
                {% set ns = namespace(reject = []) %}
                {% for group in speaker_groups_resume %}
                  {% set ns.reject = ns.reject + speaker_groups[group] %}
                {% endfor %}
                {% set reject_list = ns.reject %}
              {# determine which single playing entities are in a group which is a tts_target #}
                {% set tts_target_group = tts_target_list | select('in', speaker_group_list) | reject('in', all_speaker_groups_playing) |list %}
                {% set ns = namespace(single_resume = []) %}
                {% for group in tts_target_group %}
                  {% set ns.single_resume = ns.single_resume + speaker_groups[group] | select('in', all_players_playing) | list %}
                {% endfor %}
                {% set single_resume_list = ns.single_resume %}
              {# combine all the above to a list of players which should be resumed #}
                {% set players_resume = (tts_playing + speaker_groups_resume + single_resume_list) | reject('in', reject_list) | unique | list %}
                {% set ns = namespace(info=[]) %}
                {% for entity in expand(players_resume) %}
                  {% set ns.info = ns.info +  [ 
                                                dict(
                                                  entity_id = entity.entity_id,
                                                  friendly_name = entity.attributes.friendly_name, 
                                                  media_content_id = entity.attributes.media_content_id | default('no media_content'),
                                                  media_title = entity.attributes.media_title | default('no title'),
                                                  media_artist = entity.attributes.media_artist | default('No artist'),
                                                  media_content_type = entity.attributes.media_content_type | default('no type'),
                                                  app_name = entity.attributes.app_name | default('no app'),
                                                  entity_picture = entity.attributes.entity_picture | default('no pic'),
                                                  volume_level = entity.attributes.volume_level | round(2) 
                                                  )
                                              ] 
                  %}
                {% endfor %}
                {{ ns.info }}
            {% endif %}
```

With this:
```yaml
        all_media_player_states: >
          {% set ns = namespace(info=[]) %}
          {% for entity in states.media_player %}
            {% set ns.info = ns.info +  [ 
                                          dict(
                                            entity_id = entity.entity_id,
                                            state = entity.state
                                            )
                                        ] 
            %}
          {% endfor %}
          {{ ns.info }}
        all_players_playing: >
          {% 
            set all_players_playing = states.media_player 
                                        | selectattr('state', 'eq', 'playing') 
                                        | map(attribute='entity_id') 
                                        | list  
          %}
          {{ all_players_playing }}
        all_speaker_groups_playing: >
          {% 
            set all_speaker_groups_playing =  voice_groups | default(
                                              all_players_playing 
                                                | select('in', speaker_group_list) 
                                                | list )
          %}
          {{ all_speaker_groups_playing }}
        tts_playing: >
          {% set ns = namespace(tts_targets = []) %}
            {% for target in tts_target_list %}
              {% set ns.tts_targets = ns.tts_targets + speaker_groups[target] if target in speaker_group_list else [ target ] %}
            {% endfor %}
          {% set tts_playing = ns.tts_targets | select('in', all_players_playing) | list %}
          {{ tts_playing }}
        speaker_groups_resume: >
          {% set ns = namespace(groups = []) %}
            {% for group in all_speaker_groups_playing %}
              {% for entity in speaker_groups[group] if entity in tts_playing %}
                {% set ns.groups = ns.groups + [group] %}
              {% endfor %}
            {% endfor %}
          {% set speaker_groups_resume = ns.groups | unique | list %}
          {% set ns = namespace(groups = []) %}
            {% for target in tts_target_list %}
              {% set ns.groups = ns.groups + 
                  (sub_groups[target] | select('in', all_speaker_groups_playing) | list)
                  if sub_groups is defined else []     
            %}
            {% endfor %}
          {% set speaker_groups_resume = speaker_groups_resume + ns.groups | unique | list %}
          {{ speaker_groups_resume }}
        reject_list: >
          {% set ns = namespace(reject = []) %}
          {% for group in speaker_groups_resume %}
            {% set ns.reject = ns.reject + speaker_groups[group] %}
          {% endfor %}
          {% set reject_list = ns.reject %}
          {{ reject_list }}
        single_resume_list: >
          {% set tts_target_group = tts_target_list | select('in', speaker_group_list) | reject('in', all_speaker_groups_playing) |list %}
          {% set ns = namespace(single_resume = []) %}
          {% for group in tts_target_group %}
            {% set ns.single_resume = ns.single_resume + speaker_groups[group] | select('in', all_players_playing) | list %}
          {% endfor %}
          {% set single_resume_list = ns.single_resume %}
          {{ single_resume_list }}
        players_to_resume: >
          {# use data from google_home_say_voice script in case it was used #}
            {% if voice_media_player_data is defined %}
              {{ voice_media_player_data }}
            {% else %}
                {% set players_resume = (tts_playing + speaker_groups_resume + single_resume_list) | reject('in', reject_list) | unique | list %}
                {% set ns = namespace(info=[]) %}
                {% for entity in expand(players_resume) %}
                  {% set ns.info = ns.info +  [ 
                                                dict(
                                                  entity_id = entity.entity_id,
                                                  friendly_name = entity.attributes.friendly_name, 
                                                  media_content_id = entity.attributes.media_content_id | default('no media_content'),
                                                  media_title = entity.attributes.media_title | default('no title'),
                                                  media_artist = entity.attributes.media_artist | default('No artist'),
                                                  media_content_type = entity.attributes.media_content_type | default('no type'),
                                                  app_name = entity.attributes.app_name | default('no app'),
                                                  entity_picture = entity.attributes.entity_picture | default('no pic'),
                                                  volume_level = entity.attributes.volume_level | round(2) 
                                                  )
                                              ] 
                  %}
                {% endfor %}
                {{ ns.info }}
            {% endif %}
```

**Comment by johannwilken** [comment] 2022-01-09 07:37
Good morning Fes,

Replaced and tests conducted:

All test conducted with same results. Hopefully there is enough info in the jsons.

Multiple media players in config:
![Test 1 Service Call](https://user-images.githubusercontent.com/65971874/148673225-7c91463c-1041-4f6c-be84-5e8fd43becf6.JPG)

Test 1:
johann_wilken on master_bedroom_speaker - did resume 100%
[Test 1.zip](https://github.com/TheFes/HA-configuration/files/7834595/Test.1.zip)

Test 2:
johann_wilken on kitchen_display - did not resume
[Test 2.zip](https://github.com/TheFes/HA-configuration/files/7834597/Test.2.zip)

Test 3:
elandi on kitchen_display - did not resume
[Test 3.zip](https://github.com/TheFes/HA-configuration/files/7834600/Test.3.zip)

Test 4:
elandi on master_bedroom_speaker - did resume 100%
[Test 4.zip](https://github.com/TheFes/HA-configuration/files/7834605/Test.4.zip)

Test 5:
johann_wilken on wilken_speakers (group) - did resume 100%
[Test 5.zip](https://github.com/TheFes/HA-configuration/files/7834606/Test.5.zip)

Test 6:
elandi on wilken_speakers (group) - did resume 100%
[Test 6.zip](https://github.com/TheFes/HA-configuration/files/7834609/Test.6.zip)

------------------------------------------------------
Multiple Media Players in config flipped:
![Service call _ multiple media players flipped](https://user-images.githubusercontent.com/65971874/148673258-f61d3b0c-39b3-47b2-9200-4c15f26ca846.JPG)

Test 10:
johann_wilken on master_bedroom_speaker - did not resume (did resume 100% in Test 1)
[Test 10.zip](https://github.com/TheFes/HA-configuration/files/7834612/Test.10.zip)

Test 11:
johann_wilken on kitchen_display - did resume 100% (did not resume in Test2)
[Test 11.zip](https://github.com/TheFes/HA-configuration/files/7834615/Test.11.zip)

Test 12:
elandi on kitchen_display - did resume 100% (did not resume in Test3)
[Test 12.zip](https://github.com/TheFes/HA-configuration/files/7834617/Test.12.zip)

Test 13:
elandi on master_bedroom_speaker - did not resume (did resume 100% in Test4)
[Test 13.zip](https://github.com/TheFes/HA-configuration/files/7834620/Test.13.zip)

**Comment by TheFes** [comment] 2022-01-09 20:13
Well, that was helpful 👍  only needed one faulty test :wink: The separate variables really helped in determining in which part the error was.

Basically you were right, only the last player of the list was resumed, because the for loop I was using was overwriting the others (because of missing parentheses).

It should be fixed now if you use the latest version on Github.

**Comment by johannwilken** [comment] 2022-01-09 20:17
Hi Fes,

Thank you for your time. I will test tomorrow and let you know.

Hope you have a great week.

Regards.

**Comment by johannwilken** [comment] 2022-01-11 05:25
Good morning Fes,

Now its working like a charm. Thank you so much for this script and the time you put in for it to
work. Please feel free to ask if in the future you need something tested, I would happily do so.

Hope you have a great week?

Kind regards,

**Comment by TheFes** [comment] 2022-01-11 09:05
My week is great, especially now since I can close this ticket 😉 
Hope you have a great week as well!

Thanks for the confirmation!

**Closed as completed by TheFes** 2022-01-11 09:05 UTC
Labels: bug, google home scripts
